  angular
    .module('app',[
      'ngAnimate',
      'ngSanitize',
    	'ui.bootstrap',
      //'app.core',
      //'app.cursos',
      //'app.galeria',
      //'app.formularios',
      //'app.mapa',
      //'app.contenidos'
    ]);
